### ISSUE TITLE
issue installing the relevant programmes and running it

### ISSUE THREAD

**Issue by kaumidere** [AlanJs26/goyabu-cli#1]
Hi, i may be a noob to this so i'm trying to understand or know the relevant commands to run for arch.
so far i get the following messages
➜  ~ pip install python 3 
Defaulting to user installation because normal site-packages is not writeable
WARNING: Keyring is skipped due to an exception: Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.
ERROR: Could not find a version that satisfies the requirement python
ERROR: No matching distribution found for python
➜  ~ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
➜  ~ python anime.py                
python: can't open file '/home/yaundere/anime.py': [Errno 2] No such file or directory
➜  ~ 

if you could advise on what to do it'd be cool as this interface seems a lot cooler than that of ani-cli

**Comment by AlanJs26** [comment]
First you need to make sure all dependencies are installed: python3, mpv, git
to install you need to use your system's package manager. As you said you have arch installed, so I think you use pacman 

`pacman -S mpv python git`

all the commands must be run inside the program folder, so first you need to clone the repository. 

`git clone 'https://github.com/AlanJs26/goyabu-cli' && cd goyabu-cli`

but before doing it manually, try running the install script  `./install.sh; anime` 

if does not work:

install the python modules with `python -m pip install -r requirements.txt`
and then run `python anime.py`

**Comment by kaumidere** [comment]
Hi many thanks for your help.

Odd question, but is there a way to get this in English? I’m not Portuguese.

**Comment by AlanJs26** [comment]
It took a while but I added English support
